version: "3.8"

networks:
  default:
    external: true
    name: tn-ergo-node

volumes:
  tn_ergo_node:
    external: true

services:
  # Ergo blockchain node
  node:
    image: ergoplatform/ergo:v5.0.7
    container_name: tn-ergo-node
    command: --testnet -c /etc/ergo.conf
    volumes:
      - tn_ergo_node:/home/ergo/.ergo
      - ./config/ergo.conf:/etc/ergo.conf:ro
    ports:
      - "9052:9052"
      - "9022:9022"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  # Ergo oracle-core
  core:
    build:
      context: ./oracle-core # Path to oracle-core repo
      dockerfile: ../oracle.Dockerfile # Relative to oracle-core repo
    container_name: tn-ergo-oracle-core
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - "9010:9010"
    depends_on:
      - "node"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
