version: "3.8"

networks:
  default:
    external: true
    name: ergo-node

services:
  # Ergo blockchain node
  node:
    image: ergoplatform/ergo:v5.0.20
    container_name: ergo-node
    command: --mainnet -c /etc/ergo.conf
    volumes:
      - ./node_data:/home/ergo/.ergo
      - ./node_data/ergo.conf:/etc/ergo.conf:ro
    ports:
      - "9053:9053"
      - "9030:9030"
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xms${ERGNODE_HEAP:-4G} -Xmx${ERGNODE_HEAP:-4G}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  # Ergo oracle-core
  core:
    # Uncomment below 5 lines and comment out 'image: ...' if custom building
    #build:
    #  context: ./oracle-core # Path to oracle-core repo
    #  dockerfile: ../oracle.Dockerfile # Relative to oracle-core repo
    #  args:
    #    CCARCH: ${CCARCH:-x86_64}
    image: ergoplatform/oracle-core:latest
    container_name: ergo-oracle-core
    volumes:
      - ./oracle_data:/data
    ports:
      - "9010:9010"
      - "9011:9011"
    depends_on:
      - "node"
    restart: unless-stopped
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  # Prometheus
  prometheus:
    image: prom/prometheus
    container_name: ergo-oracle-prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prom_data/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9099:9090"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: ergo-oracle-grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - '3099:3000'
    depends_on:
      - "prometheus"
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS:-admin}
      GF_FEATURE_TOGGLES_ENABLE: publicDashboards
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
    grafana:
        external: false
